Repository softeerbootcamp4th/Team4-newCar-FE, pull requests merged in 2024-07, with the labels that each got.

#2 [Feature]: README 작성
  packages/user/README.md
Labels: documentation

#3 [Feature]: 모노레포 README 삭제 및 Root README 수정
  README.md
  packages/admin/README.md
  packages/user/README.md
Labels: documentation

#4 [Feature] shadcn path설정
  packages/admin/components.json
Labels: bug

#7 [Feature] : 레이아웃 기초, sideBar 구현
  .eslintrc.cjs
  .vscode/settings.json
  .yarn/sdks/typescript/package.json
  .yarnrc.yml
  README.md
  package.json
  packages/admin/.yarnrc.yml
  packages/admin/components.json
  packages/admin/package.json
  packages/admin/src/components/appLayout/SideBar.tsx
  packages/admin/src/components/appLayout/SideBarContainer.tsx
  packages/admin/src/components/common/ActionModal.tsx
  packages/admin/src/components/ui/accordion.tsx
  packages/admin/src/components/ui/button.tsx
  packages/admin/src/components/ui/dialog.tsx
  packages/admin/src/components/ui/input.tsx
  packages/admin/src/components/ui/label.tsx
  packages/admin/src/constants/routePath.ts
  packages/admin/src/constants/sideBarRoutes.ts
  packages/admin/src/layouts/appLayout.tsx
  packages/admin/src/libs/index.tsx
  packages/admin/src/libs/query/index.tsx
  packages/admin/src/pages/events/eventPage.tsx
  packages/admin/src/routes/router.tsx
  packages/admin/src/utils/cn.ts
  packages/admin/tailwind.config.js
  packages/admin/tsconfig.json
  packages/user/package.json
  packages/user/src/components/ui/button.tsx
  packages/user/src/constants/routePath.ts
  packages/user/src/libs/index.tsx
  packages/user/src/libs/query/index.tsx
  packages/user/src/routes/router.tsx
  packages/user/src/utils/cn.ts
  packages/user/tsconfig.json
  packages/user/vite.config.ts
  postcss.config.js
  prettier.config.cjs
  tailwind.config.cjs
  tsconfig.json
  yarn.lock
Labels: enhancement

#9 [Feature] : 헤더 스타일 구현
  packages/admin/package.json
  packages/admin/src/components/appLayout/Header.tsx
  packages/admin/src/components/appLayout/SideBar.tsx
  packages/admin/src/components/appLayout/SideBarContainer.tsx
  packages/admin/src/components/ui/accordion.tsx
  packages/admin/src/constants/headerTitles.ts
  packages/admin/src/constants/sideBarRoutes.ts
  packages/admin/src/layouts/appLayout.tsx
  packages/admin/src/pages/events/eventPage.tsx
  packages/admin/src/routes/router.tsx
  packages/admin/src/types/appLayout/types.ts
  packages/admin/tailwind.config.js
  packages/user/tsconfig.json
  yarn.lock
Labels: enhancement, style

#24 [Feature][Task-90] Admin 페이지 퍼블리싱 ( 기대평 관리 제외 )
  .DS_Store
  .eslintrc.cjs
  package.json
  packages/.DS_Store
  packages/admin/src/components/appLayout/SideBar.tsx
  packages/admin/src/components/appLayout/System.tsx
  packages/admin/src/components/common/ActionModal.tsx
  packages/admin/src/components/common/Alert.tsx
  packages/admin/src/components/common/Pagination.tsx
  packages/admin/src/components/common/Tab.tsx
  packages/admin/src/components/editor/QuizEventEditor.tsx
  packages/admin/src/components/editor/RaceEventEditor.tsx
  packages/admin/src/components/table/ResultTable.tsx
  packages/admin/src/components/ui/accordion.tsx
  packages/admin/src/components/ui/pagination.tsx
  packages/admin/src/components/ui/table.tsx
  packages/admin/src/constants/api.ts
  packages/admin/src/constants/routePath.ts
  packages/admin/src/constants/sideBarRoutes.ts
  packages/admin/src/hooks/useCustomState.tsx
  packages/admin/src/hooks/useEvent.tsx
  packages/admin/src/layouts/appLayout.tsx
  packages/admin/src/libs/index.tsx
  packages/admin/src/pages/events/CommonEventTab.tsx
  packages/admin/src/pages/events/EventsPage.tsx
  packages/admin/src/pages/events/QuizEventTab.tsx
  packages/admin/src/pages/events/RaceEventTab.tsx
  packages/admin/src/pages/events/eventPage.tsx
  packages/admin/src/pages/winner/QuizWinnerDraw.tsx
  packages/admin/src/pages/winner/WinnerResult.tsx
  packages/admin/src/routes/router.tsx
  packages/admin/src/services/api/mock/common-event.json
  packages/admin/src/services/api/mock/quiz.json
  packages/admin/src/services/api/mock/winners.json
  packages/admin/src/services/api/types/apiType.ts
  packages/admin/src/store/provider/AlertProvider.tsx
  packages/admin/src/store/provider/ModalProvider.tsx
  packages/admin/src/store/types/ModalContextType.ts
  packages/admin/src/utils/fetchData.ts
  packages/admin/src/utils/time.ts
  packages/admin/tsconfig.json
  yarn.lock
Labels: enhancement, style

#27 [Feature][Task-43] Header 데이터 동적 수정
  packages/admin/src/hooks/useHeader.tsx
  packages/admin/src/layouts/appLayout.tsx
  packages/admin/src/routes/router.tsx
Labels: enhancement

#29 [Feature][Task-59] 어드민 로그인 페이지 퍼블리싱
  packages/admin/src/constants/routePath.ts
  packages/admin/src/layouts/appLayout.tsx
  packages/admin/src/libs/index.tsx
  packages/admin/src/pages/start/LoginPage.tsx
  packages/admin/src/routes/router.tsx
Labels: enhancement

#30 [Feature][Task-41] 전체 레이아웃 구현 (지민님 -> 성락현 재할당)
  packages/admin/src/constants/routePath.ts
  packages/admin/src/hooks/useHeader.tsx
  packages/admin/src/layouts/appLayout.tsx
  packages/admin/src/libs/index.tsx
  packages/admin/src/pages/start/LoginPage.tsx
  packages/admin/src/routes/router.tsx
Labels: enhancement
