Repository softeerbootcamp4th/Team4-newCar-FE, pull requests merged in 2024-08, with the labels that each got.

#31 [Feature][Task-121] Mocking, Refactoring
  packages/admin/src/components/appLayout/SideBar.tsx
  packages/admin/src/components/appLayout/SideBarContainer.tsx
  packages/admin/src/components/editor/RaceEventEditor.tsx
  packages/admin/src/components/table/ResultTable.tsx
  packages/admin/src/constants/api.ts
  packages/admin/src/constants/sideBarRoutes.ts
  packages/admin/src/hooks/useEvent.tsx
  packages/admin/src/layouts/appLayout.tsx
  packages/admin/src/pages/events/RaceEventTab.tsx
  packages/admin/src/pages/winner/WinnerResult.tsx
  packages/admin/src/services/api/mock/personality-test-list.json
  packages/admin/src/services/api/mock/quiz-list.json
  packages/admin/src/services/api/mock/quiz.json
  packages/admin/src/services/api/mock/racing-winners.json
  packages/admin/src/services/api/mock/winners.json
  packages/admin/src/services/api/types/apiType.ts
Labels: enhancement, style

#34 [Feature][Task-90] 어드민 API 연결
  packages/admin/src/components/common/ActionModal.tsx
  packages/admin/src/components/editor/QuizEventEditor.tsx
  packages/admin/src/components/editor/RaceEventEditor.tsx
  packages/admin/src/components/table/ResultTable.tsx
  packages/admin/src/constants/api.ts
  packages/admin/src/constants/categoryList.ts
  packages/admin/src/constants/routePath.ts
  packages/admin/src/constants/sideBarRoutes.ts
  packages/admin/src/hooks/useEvent.tsx
  packages/admin/src/main.tsx
  packages/admin/src/pages/events/CommonEventTab.tsx
  packages/admin/src/pages/events/QuizEventTab.tsx
  packages/admin/src/pages/events/RaceEventTab.tsx
  packages/admin/src/pages/winner/RaceWinnerDraw.tsx
  packages/admin/src/pages/winner/WinnerResult.tsx
  packages/admin/src/routes/router.tsx
  packages/admin/src/services/api/types/apiType.ts
  packages/admin/src/utils/fetchData.ts
  packages/admin/src/utils/time.ts
Labels: bug, enhancement

#37 [Feature][Task-81] Build 이미지 번들링 이슈 대응, React-Helmet(OG) 적용
  package.json
  packages/user/index.html
  packages/user/public/favicon/favicon.ico
  packages/user/public/images/background/background.png
  packages/user/public/images/card/leisure.png
  packages/user/public/images/card/pet.png
  packages/user/public/images/card/place.png
  packages/user/public/images/card/travel.png
  packages/user/public/images/hint/1.png
  packages/user/public/images/hint/2.png
  packages/user/public/images/hint/3.png
  packages/user/public/images/prize/1.png
  packages/user/public/images/prize/2.png
  packages/user/public/images/prize/3.png
  packages/user/public/images/prize/4.png
  packages/user/public/images/prize/5.png
  packages/user/public/images/quiz/gift.png
  packages/user/public/images/quiz/popup.png
  packages/user/public/images/step/1-1.png
  packages/user/public/images/step/1-2.png
  packages/user/public/images/step/1-3.png
  packages/user/public/images/step/2-1.png
  packages/user/public/images/step/2-2.png
  packages/user/public/images/step/3.png
  packages/user/public/images/team-modal/leisure-1.png
  packages/user/public/images/team-modal/leisure-2.png
  packages/user/public/images/team-modal/pet-1.png
  packages/user/public/images/team-modal/pet-2.png
  packages/user/public/images/team-modal/place-1.png
  packages/user/public/images/team-modal/place-2.png
  packages/user/public/images/team-modal/travel-1.png
  packages/user/public/images/team-modal/travel-2.png
  packages/user/src/components/home/EventPrizes.tsx
  packages/user/src/components/home/eventHero/LandingTitle.tsx
  packages/user/src/components/home/eventHero/racing/Background.tsx
  packages/user/src/components/home/eventSteps/StepFirst.tsx
  packages/user/src/components/home/eventSteps/StepSecond.tsx
  packages/user/src/components/home/eventSteps/StepThird.tsx
  packages/user/src/components/home/fastestQuiz/QuizImages.tsx
  packages/user/src/components/home/quizHint/HintCards.tsx
  packages/user/src/components/home/teamsDescriptions/teamDescriptionModal/index.tsx
  packages/user/src/components/shared/linkShare/LinkShareMetaTag.tsx
  packages/user/src/components/shared/teamCard/index.tsx
  packages/user/src/constants/teamDescriptions.ts
  packages/user/src/libs/index.tsx
  packages/user/src/routes/router.tsx
  packages/user/vite.config.ts
  yarn.lock
Labels: bug, enhancement

#40 [Feature][Task-158] UX 개선 & 빌드 용량 축소
  .gitignore
  packages/common/src/components/chat/ChatList.tsx
  packages/user/package.json
  packages/user/public/images/hero/highlight.png
  packages/user/public/images/hero/khaki-car.png
  packages/user/public/images/hero/khaki-shadow.png
  packages/user/public/images/hero/orange-car.png
  packages/user/public/images/hero/orange-shadow.png
  packages/user/public/images/hero/white-car.png
  packages/user/public/images/hero/white-shadow.png
  packages/user/src/assets/icons/highlight.svg
  packages/user/src/assets/landing-racing/khaki-car.png
  packages/user/src/assets/landing-racing/khaki-shadow.svg
  packages/user/src/assets/landing-racing/orange-car.png
  packages/user/src/assets/landing-racing/orange-shadow.svg
  packages/user/src/assets/landing-racing/white-car.png
  packages/user/src/assets/landing-racing/white-shadow.svg
  packages/user/src/components/common/InViewLoadSection.tsx
  packages/user/src/components/common/toast/Toast.tsx
  packages/user/src/components/event/chatting/Chat.tsx
  packages/user/src/components/home/eventHero/LandingTitle.tsx
  packages/user/src/components/home/eventHero/index.tsx
  packages/user/src/components/home/eventHero/racing/Cars.tsx
  packages/user/src/components/home/fastestQuiz/index.tsx
  packages/user/src/components/home/teamsDescriptions/HoverAnimationWrapper.tsx
  packages/user/src/components/layout/banner/ScrollToQuizButton.tsx
  packages/user/src/components/layout/header/tab/index.tsx
  packages/user/src/components/layout/index.tsx
  packages/user/src/constants/quizSectionId.ts
  packages/user/src/constants/sectionId.ts
  packages/user/src/hooks/useIntersectionObserver.ts
  packages/user/src/pages/HomePage.tsx
  packages/user/src/routes/router.tsx
  packages/user/src/styles/index.css
  packages/user/vite.config.ts
  yarn.lock
Labels: enhancement

#41 [Feature][Task-81] cloudfront 배포(OG 이미지용)
  .github/workflows/deploy.yml
  package.json
  packages/admin/src/pages/start/LoginPage.tsx
  packages/common/package.json
  packages/user/index.html
  packages/user/public/link/leisure.html
  packages/user/public/link/og-leisure.png
  packages/user/public/link/og-pet.png
  packages/user/public/link/og-space.png
  packages/user/public/link/og-travel.png
  packages/user/public/link/pet.html
  packages/user/public/link/space.html
  packages/user/public/link/travel.html
  packages/user/src/components/shared/linkShare/LinkShareMetaTag.tsx
  packages/user/src/constants/teamDescriptions.ts
  packages/user/src/libs/index.tsx
  packages/user/src/routes/router.tsx
  yarn.lock
Labels: enhancement

#38 [Feature][Task-140] 어드민 API 수정 및 미비된 기능 추가
  package.json
  packages/admin/index.html
  packages/admin/package.json
  packages/admin/src/components/editor/RaceEventEditor.tsx
  packages/admin/src/components/table/ResultTable.tsx
  packages/admin/src/constants/api.ts
  packages/admin/src/constants/message.ts
  packages/admin/src/hooks/useAuth.tsx
  packages/admin/src/hooks/useEvent.tsx
  packages/admin/src/pages/events/CommonEventTab.tsx
  packages/admin/src/pages/events/QuizEventTab.tsx
  packages/admin/src/pages/start/LoginPage.tsx
  packages/admin/src/pages/winner/RaceWinnerDraw.tsx
  packages/admin/src/pages/winner/WinnerResult.tsx
  packages/admin/src/services/api/mock/common-event.json
  packages/admin/src/services/api/types/apiType.ts
  packages/admin/src/utils/fetchData.ts
  packages/admin/src/utils/time.ts
  packages/admin/src/utils/xlsx.ts
  yarn.lock
Labels: bug, enhancement

#49 [Feature][Task-190] setCookie, getCookie 추가 및 fetchInterceptor에 AccessToken 적용
  packages/common/src/constants/api.ts
  packages/common/src/utils/api/fetchInterceptors.ts
  packages/common/src/utils/index.ts
  packages/common/src/utils/storage/cookie/getCookie.ts
  packages/common/src/utils/storage/cookie/index.ts
  packages/common/src/utils/storage/cookie/setCookie.ts
  packages/common/src/utils/storage/index.ts
Labels: enhancement

#53 [Feature][Task-139] 어드민 API 연동 & 이벤트 페이지 내 커스텀 커서 추가
  packages/admin/src/components/appLayout/SideBar.tsx
  packages/admin/src/constants/api.ts
  packages/admin/src/constants/message.ts
  packages/admin/src/constants/routePath.ts
  packages/admin/src/constants/sideBarRoutes.ts
  packages/admin/src/hooks/useAuth.tsx
  packages/admin/src/hooks/useEvent.tsx
  packages/admin/src/layouts/appLayout.tsx
  packages/admin/src/pages/review/Review.tsx
  packages/admin/src/routes/router.tsx
  packages/admin/src/services/api/types/apiType.ts
  packages/admin/src/utils/fetchData.ts
  packages/common/src/constants/index.ts
  packages/common/src/utils/api/fetchInterceptors.ts
  packages/common/src/utils/api/index.ts
  packages/user/index.html
  packages/user/public/cursor/cursor-100.png
  packages/user/public/link/leisure.html
  packages/user/public/link/og-default.png
  packages/user/public/link/og-leisure.png
  packages/user/public/link/og-space.png
  packages/user/public/link/og-travel.png
  packages/user/public/link/pet.html
  packages/user/public/link/space.html
  packages/user/public/link/travel.html
  packages/user/src/App.tsx
  packages/user/src/components/cursor/CasperCursor.tsx
  packages/user/src/hooks/useCorusr.ts
  packages/user/src/main.tsx
  packages/user/src/styles/index.css
Labels: enhancement

#85 [Feature][Task-171] Xlsx 버전 upgrade, 마우스 커서 버그 수정
  package.json
  packages/admin/package.json
  packages/admin/src/pages/winner/WinnerResult.tsx
  packages/admin/src/services/socket.ts
  packages/user/public/cursor/cursor-100.png
  packages/user/public/cursor/cursor-50.png
  packages/user/src/components/cursor/CasperCursor.tsx
  packages/user/src/components/shared/modal/fcfs/ErrorStep.tsx
  packages/user/src/hooks/useCursor.ts
  packages/user/src/styles/index.css
  yarn.lock
Labels: bug, enhancement

#88 [Feature][Task-263] 커서 변경, 플립 애니메이션 제거, 소켓 연결
  .github/workflows/deploy.yml
  packages/admin/src/hooks/socket/useChatSocket.ts
  packages/user/public/cursor/cursor-50.png
  packages/user/src/components/cursor/CasperCursor.tsx
  packages/user/src/components/shared/timer/TimeUnit.tsx
  yarn.lock
Labels: bug

#93 [Feature][Task-42] Notice, Block 송수신 방식 수정
  packages/admin/src/components/chat/Chat.tsx
  packages/admin/src/components/chat/RealTimeChatting.tsx
  packages/admin/src/constants/api.ts
  packages/admin/src/hooks/socket/index.ts
  packages/admin/src/hooks/socket/useChatSocket.ts
  packages/admin/src/main.tsx
  packages/admin/src/services/socket.ts
  packages/common/src/constants/socket.ts
  packages/user/src/hooks/socket/useChatSocket.ts
  packages/user/src/services/socket.ts
Labels: bug, documentation

#103 [Feature][Task-42] 채팅 히스토리 패치 작업
  packages/admin/src/components/chat/RealTimeChatting.tsx
  packages/admin/src/hooks/socket/index.ts
  packages/admin/src/hooks/socket/useChatSocket.ts
  packages/admin/src/pages/review/Review.tsx
  packages/admin/src/services/eventBus.ts
  packages/admin/src/services/socket.ts
  packages/common/src/constants/socket.ts
  packages/user/src/services/socket.ts
Labels: bug, enhancement

#108 [Feature][Task-42] 8.21일 QA 수정
  packages/admin/src/components/chat/Chat.tsx
  packages/admin/src/components/chat/RealTimeChatting.tsx
  packages/admin/src/components/error/CommonErrorBoundary.tsx
  packages/admin/src/hooks/socket/useChatSocket.ts
  packages/admin/src/hooks/useEvent.tsx
  packages/admin/src/layouts/appLayout.tsx
  packages/admin/src/libs/index.tsx
  packages/admin/src/pages/winner/WinnerResult.tsx
  packages/admin/src/services/socket.ts
  packages/common/src/constants/socket.ts
  packages/user/src/services/socket.ts
Labels: bug, enhancement

#117 [Feature][Task-42] QA 수정사항 반영
  packages/admin/index.html
  packages/admin/public/favicon/favicon.ico
  packages/admin/src/App.tsx
  packages/admin/src/components/error/CommonErrorBoundary.tsx
  packages/admin/src/hooks/socket/useChatSocket.ts
  packages/admin/src/layouts/appLayout.tsx
  packages/user/src/components/home/teamsDescriptions/index.tsx
Labels: bug
